// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5XJW3VDwEAEC6urFxmX1ydXVHV6dL2zo',
    appId: '1:173797885480:android:ac9757d230a3a4b921d71d',
    messagingSenderId: '173797885480',
    projectId: 'ecommerce-12-d1289',
    storageBucket: 'ecommerce-12-d1289.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWnEcZKPHqtMRU1ShIiX2gHw7UjS3TZI0',
    appId: '1:173797885480:ios:8b99c11f5eb89e1721d71d',
    messagingSenderId: '173797885480',
    projectId: 'ecommerce-12-d1289',
    storageBucket: 'ecommerce-12-d1289.appspot.com',
    androidClientId: '173797885480-ej0p59vefcsfu1g6liulscgk1g1sr0nr.apps.googleusercontent.com',
    iosClientId: '173797885480-laip6cunk0ab3gnflf9vovnkp05s9jlc.apps.googleusercontent.com',
    iosBundleId: 'site.tunckankilic.tkecommerce',
  );
}
